### ISSUE TITLE
GL not found in ubuntu 14

### ISSUE THREAD

**Issue by memsharded** [coding3d/conan-glew#1]
Thanks for creating this package!

```bash
glew/1.13.0@coding3d/ci: Generated cmake created conanbuildinfo.cmake
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindOpenGL.cmake:161 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:39 (find_package)
```

I guess I need to install some system lib. That can be done with package recipe ``system_requirements()`` automatically, maybe you want to add it. There are helpers to check linux distro and version.

**Comment by memsharded** [comment]
It seems installing these is enough:
- mesa-common-dev
- libglu1-mesa-dev

**Comment by coding3d** [comment]
You're welcome! I think you need to install something like mesa dev, and
libgl1 or something like that. I don't remember the exact names and I am
not with my computer right now. :D I will document it.

Le 20 août 2016 20:05, "James" <notifications@github.com> a écrit :

It seems installing these is enough:

   - mesa-common-dev
   - libglu1-mesa-dev

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/coding3d/conan-glew/issues/1#issuecomment-241214694>,
or mute the thread

**Comment by coding3d** [comment]
Or better even I will use the reqs function as you suggested (still
learning, so I didn't know about it)

**Comment by coding3d** [comment]
Hi James,

I have [added a system_requirements function](https://github.com/coding3d/conan-glew/commit/148d456578d69df15283de63702ca6d79a4bd4bf) to conanfile.py. I have one question though.

Testing conan-glew locally, system_requirements only ran after I explicitly called it from within conanfile.py's build function. Is it supposed to be called automatically by conan, for instance when I execute "conan test_package"? And could you please let me know if the same applies for the "source" function? I've noticed for example that [lasote is declaring both of these functions](https://github.com/lasote/conan-sdl2/blob/master/conanfile.py), but he never calls them from within conanfile.py and I am wondering why they never get executed automatically on my system, if they are supposed to.

**Comment by BenStraubinger** [comment]
This check fails on non-debian based distros.

For reference, my Fedora 23 x64 uses the following packages:
```
mesa-libGL-devel
mesa-libGLU-devel
```

:Could you please update to check based on distro / package manager?

If `rpm` is available, you can check with: 
`$ rpm -qa | grep "mesa-libGL-devel\|mesa-libGLU-devel"`

Let me know if you need any help. I'll keep an eye out for a fix and confirm once verified.
